# Generated by Django 4.1.4 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='sleep',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='room',
            name='childrens',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='overview',
            field=models.TextField(default='', null=True),
        ),
    ]
