# Generated by Django 4.1.4 on 2023-02-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyRooms', to='hotels.property'),
        ),
    ]
