# Generated by Django 4.1.4 on 2023-02-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
    ]
